os: osx
osx_image: xcode8
language: objective-c
rvm:
    2.2.5
cache:
    - bundler
    - cocoapods
before_install:
    - gem install xcpretty
script:
    - set -o pipefail && xcodebuild test -workspace GameOfLife.xcworkspace -scheme GameOfLife -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'GameOfLife'
